### ISSUE TITLE
gcc-first doesn't build with gcc4.7 system compiler

### ISSUE THREAD

**Issue by bradtgmurray** [jsnyder/arm-eabi-toolchain#21]
Using gcc 4.7, which is the default for Fedora 17.

Looks like we run into this bug here: http://gcc.gnu.org/bugzilla/show_bug.cgi?id=51969

I don't know if the correct answer is patch the codesourcery version of gcc or to look for an updated codesourcery package with this bug fixed.

**Comment by bradtgmurray** [comment]
Here's the resulting error message that stops compilation.

```
gcc -c   -g -O2 -DIN_GCC -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-format-attribute -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -Wold-style-definition -Wc++-compat   -DHAVE_CONFIG_H -I. -I. -I../../../gcc-4.6-2011.09/gcc -I../../../gcc-4.6-2011.09/gcc/. -I../../../gcc-4.6-2011.09/gcc/../include -I../../../gcc-4.6-2011.09/gcc/../libcpp/include  -I../../../gcc-4.6-2011.09/gcc/../libdecnumber -I../../../gcc-4.6-2011.09/gcc/../libdecnumber/dpd -I../libdecnumber     gtype-desc.c -o gtype-desc.o
gtype-desc.c:8840:18: error: subscripted value is neither array nor pointer nor vector
gtype-desc.c:8959:36: error: subscripted value is neither array nor pointer nor vector
gtype-desc.c:9043:31: error: subscripted value is neither array nor pointer nor vector
gtype-desc.c:9064:31: error: subscripted value is neither array nor pointer nor vector
gtype-desc.c:9071:31: error: subscripted value is neither array nor pointer nor vector
gtype-desc.c:9078:31: error: subscripted value is neither array nor pointer nor vector
make[3]: *** [gtype-desc.o] Error 1
make[3]: Leaving directory `/home/brad/vcs/arm-eabi-toolchain/build/gcc-first/gcc'
make[2]: *** [all-gcc] Error 2
make[2]: Leaving directory `/home/brad/vcs/arm-eabi-toolchain/build/gcc-first'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/brad/vcs/arm-eabi-toolchain/build/gcc-first'
make: *** [cross-gcc-first] Error 2
```

**Comment by jsnyder** [comment]
What's in there is currently the latest version ( https://sourcery.mentor.com/GNUToolchain/subscription3053 ).  If the patch is actually a fix and doesn't break building on previous versions of GCC or other compilers, I'm happy to just include the patch until it's fixed in a future Mentor/Sourcery release.

I've put a version that includes this patch in the following branch: oos_newv_patch

If you could let me know if that works.  I'll also do some checking on my usual test platforms when I get a little time.

**Comment by bradtgmurray** [comment]
Thanks for the quick response.

Do you mind changing your patch line to pushd ... && patch ... && popd (from pushd ... ; patch ... ; popd)? It took me awhile to figure out that I didn't actually have patch installed on my fresh VM. I'm trying to rebuild now, I'll let you know how that goes.

**Comment by bradtgmurray** [comment]
This branch ended up working perfectly once I got the required dependancies installed. Thanks!

**Comment by jsnyder** [comment]
Thanks!  I've pushed that up now including the && (though that has a strange side effect of returning non-zero even with the "Ignore patches that seem to be reversed  or  already  applied." -N flag set.  One can make clean to blow away the whole tree + patched files though.
