### ISSUE TITLE
duplicate symbol _cpp_relocated in libbackend.a

### ISSUE THREAD

**Issue by zippy78753** [jsnyder/arm-eabi-toolchain#11]
failing to build on my OSX 10.6.8 box

ld: duplicate symbol _cpp_relocated in libbackend.a(cppdefault.o) and cppdefault.o for architecture x86_64
collect2: ld returned 1 exit status
make[3]: **\* [cc1plus-dummy] Error 1
make[3]: **\* Waiting for unfinished jobs....
make[2]: **\* [all-gcc] Error 2
make[1]: **\* [all] Error 2
make: **\* [cross-g++] Error 2
rm arm-2010q1-188-arm-none-eabi/binutils-2010q1-188.tar.bz2 arm-2010q1-188-arm-none-eabi/newlib-2010q1-188.tar.bz2

**Comment by zippy78753** [comment]
I was modifying the Makefile to build an older version of the toolchain (2010q1-188).  It seems that the latest Makefile cannot build that version of the toolchain.  I reverted to revision cc2956464371f856b5cd, which is the last version that had 2010q1-188 as the default in the Makefile, and I can build the toolchain just fine
